[theme]
# Background color for the main content area.
backgroundColor = "#000000"

# Primary accent color for interactive elements.
primaryColor = "#40E0D0"

# Color used for almost all text.
textColor = "#fff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#110c11"